"""
One-time script to replace all products with the 20 new tops products.
Run from the backend directory: python reset_products.py
"""
import sqlite3
import json
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent / "toplable.db"
BASE_URL = "http://localhost:8000/static/products"

NEW_PRODUCTS = [
    {
        "name": "Classic White T-Shirt",
        "price": 2500,
        "category": "tops",
        "description": "Premium cotton t-shirt with a modern fit. A versatile everyday essential crafted from soft, breathable cotton fabric.",
        "image_url": f"{BASE_URL}/white-tshirt.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["white", "black", "gray"],
        "stock": 11,
        "size_stock": {"S": 3, "M": 4, "L": 3, "XL": 1},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Calvin Klein Monologo Long Sleeve Slim Tee",
        "price": 16500,
        "category": "tops",
        "description": "A classic, versatile essential crafted from soft cotton jersey. This long-sleeve tee features a slim-fit silhouette with a ribbed crew neckline and the iconic Calvin Klein 'CK' monologo printed in contrasting red on the chest. Perfect for layering or as a clean, standalone piece for casual wear.",
        "image_url": f"{BASE_URL}/97e9d8a5a18642c6b16e85a20e3c0229.png",
        "image_gallery": [
            f"{BASE_URL}/97e9d8a5a18642c6b16e85a20e3c0229.png",
            f"{BASE_URL}/a2aadf7fdb2c4c9b89cfd2eb7707e00d.jpg",
            f"{BASE_URL}/4e8e43ea2da74595a1bb3b7d0f0f6b79.png",
        ],
        "sizes": ["XS", "S", "M", "L"],
        "colors": ["black", "gray", "white"],
        "stock": 3,
        "size_stock": {"XS": 1, "S": 1, "M": 1, "L": 0},
        "color_size_stock": {},
        "color_images": {
            "black": f"{BASE_URL}/97e9d8a5a18642c6b16e85a20e3c0229.png",
            "gray":  f"{BASE_URL}/a2aadf7fdb2c4c9b89cfd2eb7707e00d.jpg",
            "white": f"{BASE_URL}/4e8e43ea2da74595a1bb3b7d0f0f6b79.png",
        },
    },
    {
        "name": "L'Elegance Lace-Inlay Ribbed Mock-Neck Top",
        "price": 11500,
        "category": "tops",
        "description": "Achieve sophisticated allure in this beautiful ribbed-knit top. It features a fitted, long-sleeve silhouette with a dramatic V-shaped inlay of delicate, complex black lace across the décolletage, leading up to a matching high-lace mock-neck collar. A perfect choice for evening wear layered under a blazer, or paired with a sleek skirt for a powerful, feminine look. Includes a button fastening at the back neck.",
        "image_url": f"{BASE_URL}/2730fdc2a261489d9671cc96e125dfb8.jpg",
        "image_gallery": [],
        "sizes": ["XS", "S", "M", "L"],
        "colors": ["black"],
        "stock": 5,
        "size_stock": {"XS": 1, "S": 2, "M": 1, "L": 1},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Fila Tricolor Sport Logo Tee",
        "price": 5000,
        "category": "tops",
        "description": "A classic sporty-casual tee with a bold colour block design. This short-sleeve shirt features a clean tricolor pattern with a red upper panel, a white central band, and a navy blue lower body. A prominent dark navy Fila logo is printed across the white chest band for a heritage athletic look. Made from comfortable, breathable cotton jersey.",
        "image_url": f"{BASE_URL}/b3c5de9cac6a4956b0273265c73700f5.jpg",
        "image_gallery": [],
        "sizes": ["XS"],
        "colors": ["red"],
        "stock": 0,
        "size_stock": {"XS": 0},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Ruched Off-The-Shoulder Wrap Top",
        "price": 6000,
        "category": "tops",
        "description": "A chic, sophisticated off-the-shoulder top in a rich terracotta hue. This blouse features intricate ruching across the bodice, creating a flattering, feminine silhouette. Made from a comfortable stretch-jersey fabric, it has a wide V-neckline that can be worn on or off the shoulders. Perfect for evening wear or adding a touch of elegance to a casual look.",
        "image_url": f"{BASE_URL}/e5440a7b717e4a10948536cc94b5b66f.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["terracotta"],
        "stock": 0,
        "size_stock": {"S": 0, "M": 0, "L": 0},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Multi-Pattern Floral Halter Top",
        "price": 3500,
        "category": "tops",
        "description": "A vibrant and stylish halter-neck top featuring a sophisticated blend of patterns. The top is designed with distinct horizontal bands: a dark navy band with small white floral sprigs at the top, followed by a band with dense white and blue flowers, and a large centre border separating the sections. The halter neck creates a flattering silhouette.",
        "image_url": f"{BASE_URL}/04ca0a0ca91d4fc4b1e9d34782b3c65a.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["navy"],
        "stock": 4,
        "size_stock": {"S": 2, "M": 1, "L": 1},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "GAP Classic Arch Logo T-Shirt",
        "price": 3000,
        "category": "tops",
        "description": "A definitive wardrobe essential. This short-sleeve crewneck tee is crafted from soft, comfortable cotton jersey and features the iconic GAP arch logo printed in a bold, contrasting white across the chest. Designed with a standard fit for effortless everyday style and a soft feel against the skin. Perfect for layering or wearing as a standalone statement piece.",
        "image_url": f"{BASE_URL}/4ccb4d441da946d5bc6e608b624c1964.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["navy", "white"],
        "stock": 4,
        "size_stock": {"S": 2, "M": 1, "L": 1},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Maison Scotch Voila Graphic T-Shirt",
        "price": 2900,
        "category": "tops",
        "description": "Express yourself with this chic graphic tee from Maison Scotch. Made from soft white cotton, it features a bold four-line text graphic reading VOILÀ stacked repeatedly. The text is printed in color between red, bright orange and black for a dynamic, screen-printed look. Below the main graphic, fine print reads 'GALERIE – LES FAUVES – PARIS and MAISON SCOTCH', making this a perfect statement piece for casual, elevated Parisian style.",
        "image_url": f"{BASE_URL}/d65669628a0445dfb3c421af6bce60b0.jpg",
        "image_gallery": [],
        "sizes": ["XS", "S", "M"],
        "colors": ["white"],
        "stock": 5,
        "size_stock": {"XS": 1, "S": 2, "M": 2},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Floral Long Sleeve Blouse",
        "price": 4500,
        "category": "tops",
        "description": "Elevate your wardrobe with this effortlessly stylish blouse. This versatile top features a subtle round neckline with a charming, multi-coloured ditsy floral pattern in shades of red, purple and blue on a rich navy background. The loose-fitting silhouette is perfectly complemented by soft, balloon sleeves for an effortless style. The blouse is a lightweight, breezy option that adds a touch of elegance to any outfit.",
        "image_url": f"{BASE_URL}/424c3632ee044269b9cd0bc55ce071fb.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["navy"],
        "stock": 4,
        "size_stock": {"S": 1, "M": 2, "L": 1},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Zizzi Olive Green V-Neck Sleeveless Blouse",
        "price": 7000,
        "category": "tops",
        "description": "Elevate your everyday wardrobe with this elegant sleeveless blouse by Zizzi. Crafted from a lightweight, flowy fabric, this top features a flattering V-neckline highlighted by a sophisticated center front pleat detail. The rich olive green base is complemented by a subtle, all-over speckled pattern that adds a delicate texture. With a relaxed fit and a slightly curved hem, it offers a comfortable yet polished look perfect for both casual wear and office attire.",
        "image_url": f"{BASE_URL}/16e23d8b1a4f4be18e2b8c4fada81f6a.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["olive"],
        "stock": 0,
        "size_stock": {"S": 0, "M": 0, "L": 0},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Heather Grey Paisley Motif Graphic T-Shirt",
        "price": 4500,
        "category": "tops",
        "description": "Add a touch of bohemian flair to your casual wardrobe with this relaxed-fit graphic t-shirt. Crafted from a soft, breathable heather grey cotton blend, this tee features a classic crew neckline and comfortable drop-shoulder sleeves for an effortlessly stylish, oversized look. The front showcases a large, intricate symmetrical print featuring detailed paisley and floral motifs in warm earth tones of terracotta, maroon, and subtle light blue accents.",
        "image_url": f"{BASE_URL}/aa1d563b88ab47b0a91a0efdead5f270.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["gray"],
        "stock": 0,
        "size_stock": {"S": 0, "M": 0, "L": 0},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Teal Green Maternity Tie-Front Top",
        "price": 5500,
        "category": "tops",
        "description": "Designed to flatter your growing bump, this comfortable and stylish maternity top is crafted from a soft, stretch-jersey fabric. It features a classic round neckline with a subtle keyhole detail and long sleeves. The elegant empire-waist design includes an adjustable side tie that comfortably sits just above the belly, offering a custom fit throughout your pregnancy. A perfect, versatile addition to your maternity wardrobe for both everyday wear and special occasions.",
        "image_url": f"{BASE_URL}/307a613641ed4d1f841e3015e09571a4.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["teal"],
        "stock": 3,
        "size_stock": {"S": 1, "M": 1, "L": 1},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Sienna Lace-Trim Ribbed Mock Neck Top",
        "price": 4850,
        "category": "tops",
        "description": "Elevate your essentials with this sophisticated long-sleeve top. Crafted from a soft, form-fitting ribbed knit, it features delicate floral lace detailing along the mock neckline, hem, and cuffs for a romantic, feminine touch. Perfect for layering under a blazer or wearing as a standout piece for an evening out.",
        "image_url": f"{BASE_URL}/b4fd381fd51a44aa85967d0f760cd08b.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["terracotta", "rust"],
        "stock": 8,
        "size_stock": {"S": 3, "M": 3, "L": 2},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Lavender Smocked Ruffle Yoke Blouse",
        "price": 5200,
        "category": "tops",
        "description": "A dreamy, ethereal addition to any wardrobe, this blouse features intricate smocking across the yoke and delicate ruffle trim for a vintage-inspired aesthetic. The lightweight, fluid fabric creates a relaxed silhouette with elegant pleated detailing and cuffed balloon sleeves. Finished with a subtle high neck and a button closure at the back, it is a perfect blend of modesty and modern style.",
        "image_url": f"{BASE_URL}/4f3ed740e19540109c22b3e6107f96b3.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["lavender"],
        "stock": 19,
        "size_stock": {"S": 7, "M": 7, "L": 5},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Scallop Edge Cami Top - Coffee",
        "price": 2150,
        "category": "tops",
        "description": "Elevate your basics with this chic Cami Top in a rich, warm coffee brown. Featuring a fitted, cropped silhouette and delicate spaghetti straps, it is defined by a charming scalloped edge along the V-neckline. Made from soft, breathable cotton-blend fabric, it offers both comfort and style. Ideal for layering under cardigans or wearing on its own on sunny days.",
        "image_url": f"{BASE_URL}/1b5394d84b9543419fa6f369f3be6c95.png",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["brown"],
        "stock": 10,
        "size_stock": {"S": 4, "M": 4, "L": 2},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Bright Orange Oversized Tee with Subtly Embossed Logo",
        "price": 2500,
        "category": "tops",
        "description": "Elevate your casual style with this vibrant, eye-catching oversized t-shirt. Crafted from a soft, breathable cotton blend, this tee offers both comfort and style in equal measure. The slightly dropped shoulders and relaxed fit provide a modern and laid-back silhouette, making it a perfect fit for any modern wardrobe. The standout feature is the subtle tonal embossed 'EVERYTHING' text on the left chest, adding a sophisticated touch. Perfect for a wide range of activities, from casual outings to lounging at home.",
        "image_url": f"{BASE_URL}/059f63fa8a784dcfb7fd4a4a5e575551.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["orange"],
        "stock": 7,
        "size_stock": {"S": 3, "M": 2, "L": 2},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Hot Pink Mock Neck Lettuce Edge Ribbed Top",
        "price": 2250,
        "category": "tops",
        "description": "Elevate your everyday basics with this vibrant, hot pink long-sleeved top. It features a soft, stretch ribbed-knit texture for a comfortable, figure-hugging fit. The style is defined by a mocked mock neckline and charming lettuce-edge trims on the neck, cuffs, and hem, adding a feminine touch to the minimalist design. Perfect for pairing with high-waisted shorts, skirts or trousers for an effortlessly dressy-to-casual transition.",
        "image_url": f"{BASE_URL}/9831e7c0cc654614b8e062f478ae2e0b.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["fuchsia"],
        "stock": 6,
        "size_stock": {"S": 2, "M": 2, "L": 2},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Sun-Kissed Yellow Deep V Halter Bodysuit",
        "price": 4750,
        "category": "tops",
        "description": "Elevate your everyday basics with this vibrant, sun-kissed yellow deep V halter bodysuit. This stunning piece is a masterclass in modern chic, combining a plunging deep V-neckline with a fluid, draped silhouette. The style is defined by a fluid, wide-leg transition. It is crafted from a soft, matte stretch fabric for a supportive and form-fitting construction. A wide, smooth panel under the bust defines the waist, flowing into a comfortable, classic bottom. This bodysuit features a convenient snap-button closure at the crotch.",
        "image_url": f"{BASE_URL}/143ae595bf7f4b4f8b5c074ac7034d42.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["yellow"],
        "stock": 6,
        "size_stock": {"S": 2, "M": 2, "L": 2},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Sunny Skies Off-The-Shoulder Crop Top",
        "price": 2650,
        "category": "tops",
        "description": "This charming light yellow crop top is the perfect piece for sunny days and warm evenings. Crafted from a lightweight, breathable cotton fabric, it features a classic off-the-shoulder neckline adorned with delicate ruffles. The long, balloon sleeves are gathered at the cuffs for a romantic, boho-inspired touch. The loose-fitting silhouette is perfect for layering or wearing on its own as a blouse or with jeans.",
        "image_url": f"{BASE_URL}/9fee61bb109a458ab1d47d6adf176315.jpg",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["yellow"],
        "stock": 0,
        "size_stock": {"S": 0, "M": 0, "L": 0},
        "color_size_stock": {},
        "color_images": {},
    },
    {
        "name": "Lime Green Sleeveless V-Neck Step-Hem Blouse",
        "price": 5000,
        "category": "tops",
        "description": "Elevate your summer style with this eye-catching lime green sleeveless blouse. Crafted from a soft, breathable fabric blend, it features a modern high neckline that flows into a flattering V-neck with a clean flat-pocket detail. The loose-fitting silhouette is perfectly complemented by a step-hem design that is all about comfortable confidence and effortless style. It is perfect for pairing with high-waisted jeans or a skirt for an effortless day-to-night transition.",
        "image_url": f"{BASE_URL}/56c2547600f54d5596a3767fd3c67d60.png",
        "image_gallery": [],
        "sizes": ["S", "M", "L"],
        "colors": ["lime"],
        "stock": 5,
        "size_stock": {"S": 2, "M": 2, "L": 1},
        "color_size_stock": {},
        "color_images": {},
    },
]


def reset_products():
    conn = sqlite3.connect(str(DB_PATH))
    cursor = conn.cursor()

    # Delete all existing products
    cursor.execute("DELETE FROM Products")
    cursor.execute("DELETE FROM sqlite_sequence WHERE name='Products'")
    print(f"Cleared all products.")

    # Insert new products
    for p in NEW_PRODUCTS:
        cursor.execute("""
            INSERT INTO Products (
                name, category, price, description,
                image_path, image_gallery, colors, sizes, stock,
                size_stock, color_size_stock, color_images, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
        """, (
            p["name"],
            p["category"],
            p["price"],
            p["description"],
            p["image_url"],
            json.dumps(p["image_gallery"]),
            json.dumps(p["colors"]),
            json.dumps(p["sizes"]),
            p["stock"],
            json.dumps(p["size_stock"]),
            json.dumps(p["color_size_stock"]),
            json.dumps(p["color_images"]),
        ))
        print(f"  Inserted: {p['name']}")

    conn.commit()
    conn.close()
    print(f"\nDone. {len(NEW_PRODUCTS)} products inserted.")


if __name__ == "__main__":
    reset_products()
